# -*- coding: utf-8 -*-
# Confidence scores (0-100) representing the reliability of each module's data.
# Applied automatically to events when a module does not set confidence explicitly.
# Scoring rationale:
#   90-100: Authoritative / direct registry or live-scan data
#   75-89:  Reputable third-party feeds with large datasets
#   55-74:  Derivative, aggregated, or community-sourced data
#   40-54:  Speculative techniques (brute force, pattern matching, dark web)

MODULE_CONFIDENCE = {
    # --- DNS & Network Registry (authoritative) ---
    "sfp_dnsresolve": 95,
    "sfp_dnsraw": 93,
    "sfp_dnszonexfer": 92,
    "sfp_dnscommonsrv": 80,
    "sfp_dnsneighbor": 72,
    "sfp_dnsgrep": 75,
    "sfp_dnsdb": 85,
    "sfp_arin": 92,
    "sfp_ripe": 92,
    "sfp_bgpview": 88,
    "sfp_networksdb": 82,
    "sfp_robtex": 80,
    "sfp_viewdns": 78,
    "sfp_whois": 90,
    "sfp_whoisology": 78,
    "sfp_whoxy": 78,
    "sfp_jsonwhoiscom": 78,
    "sfp_reversewhois": 75,
    "sfp_zonefiles": 78,

    # --- Active / Passive Scan Sources ---
    "sfp_shodan": 90,
    "sfp_censys": 90,
    "sfp_binaryedge": 87,
    "sfp_sslcert": 95,
    "sfp_certspotter": 90,
    "sfp_crt": 88,
    "sfp_spider": 82,
    "sfp_pageinfo": 82,
    "sfp_portscan_tcp": 92,
    "sfp_webserver": 85,
    "sfp_webframework": 80,
    "sfp_webanalytics": 78,
    "sfp_cookie": 80,
    "sfp_strangeheaders": 80,
    "sfp_builtwith": 82,
    "sfp_whatcms": 78,
    "sfp_urlscan": 84,
    "sfp_securitytrails": 88,
    "sfp_hackertarget": 80,
    "sfp_fullhunt": 80,

    # --- Threat Intelligence Feeds ---
    "sfp_virustotal": 88,
    "sfp_abuseipdb": 85,
    "sfp_abusech": 85,
    "sfp_threatfox": 85,
    "sfp_greynoise": 87,
    "sfp_greynoise_community": 82,
    "sfp_alienvault": 82,
    "sfp_alienvaultiprep": 82,
    "sfp_spamhaus": 88,
    "sfp_blocklistde": 80,
    "sfp_spamcop": 78,
    "sfp_sorbs": 75,
    "sfp_uceprotect": 72,
    "sfp_dronebl": 75,
    "sfp_greensnow": 72,
    "sfp_cinsscore": 75,
    "sfp_emergingthreats": 82,
    "sfp_threatcrowd": 75,
    "sfp_threatminer": 78,
    "sfp_threatjammer": 75,
    "sfp_pulsedive": 80,
    "sfp_maltiverse": 78,
    "sfp_malwarepatrol": 80,
    "sfp_xforce": 83,
    "sfp_talosintel": 85,
    "sfp_fortinet": 80,
    "sfp_badpackets": 80,
    "sfp_honeypot": 72,
    "sfp_botvrij": 78,
    "sfp_botscout": 72,
    "sfp_cybercrimetracker": 75,
    "sfp_vxvault": 75,
    "sfp_phishtank": 80,
    "sfp_openphish": 78,
    "sfp_phishstats": 75,
    "sfp_isc": 78,
    "sfp_mnemonic": 80,
    "sfp_onyphe": 82,
    "sfp_leakix": 80,
    "sfp_fraudguard": 78,
    "sfp_ipqualityscore": 82,
    "sfp_spur": 82,
    "sfp_metadefender": 80,
    "sfp_hybrid_analysis": 83,

    # --- IP Geolocation / Info ---
    "sfp_ipinfo": 85,
    "sfp_ipapicom": 80,
    "sfp_ipapico": 80,
    "sfp_ipregistry": 82,
    "sfp_ipstack": 78,
    "sfp_geoinfo": 80,
    "sfp_maxmind": 85,

    # --- Breach / Exposure Data ---
    "sfp_haveibeenpwned": 90,
    "sfp_dehashed": 82,
    "sfp_leakcheck": 80,
    "sfp_scylla": 75,
    "sfp_skymem": 68,
    "sfp_emailcrawlr": 72,
    "sfp_emailrep": 75,
    "sfp_debounce": 72,
    "sfp_trumail": 70,
    "sfp_nameapi": 70,

    # --- Search Engines (derivative / aggregated) ---
    "sfp_googlesearch": 72,
    "sfp_bingsearch": 70,
    "sfp_duckduckgo": 68,
    "sfp_yandexdns": 70,
    "sfp_commoncrawl": 62,
    "sfp_grep_app": 68,
    "sfp_searchcode": 65,
    "sfp_archiveorg": 60,

    # --- Social / People Data ---
    "sfp_github": 78,
    "sfp_twitter": 70,
    "sfp_instagram": 65,
    "sfp_linkedin": 65,
    "sfp_myspace": 55,
    "sfp_slideshare": 60,
    "sfp_flickr": 60,
    "sfp_gravatar": 70,
    "sfp_keybase": 72,
    "sfp_pgp": 68,
    "sfp_stackoverflow": 65,
    "sfp_socialprofiles": 65,
    "sfp_accounts": 58,

    # --- Company / Business Data ---
    "sfp_clearbit": 78,
    "sfp_fullcontact": 72,
    "sfp_company": 68,
    "sfp_opencorporates": 82,
    "sfp_gleif": 85,
    "sfp_similar": 65,
    "sfp_builtwith": 82,
    "sfp_hostio": 75,
    "sfp_spyonweb": 70,

    # --- Email Enumeration (pattern-based) ---
    "sfp_hunter": 68,
    "sfp_snov": 65,
    "sfp_emailformat": 55,
    "sfp_email": 72,

    # --- Brute Force / Speculative ---
    "sfp_dnsbrute": 55,
    "sfp_tldsearch": 52,
    "sfp_sublist3r": 62,
    "sfp_recondev": 65,
    "sfp_crobat_api": 65,
    "sfp_dnsdumpster": 68,
    "sfp_projectdiscovery": 65,
    "sfp_c99": 65,

    # --- Dark Web / Tor / Paste Sites ---
    "sfp_pastebin": 50,
    "sfp_psbdmp": 50,
    "sfp_torch": 45,
    "sfp_ahmia": 45,
    "sfp_darksearch": 45,
    "sfp_onioncity": 45,
    "sfp_onionsearchengine": 45,
    "sfp_wikileaks": 55,
    "sfp_citadel": 50,
    "sfp_intelx": 62,
    "sfp_punkspider": 60,
    "sfp_trashpanda": 55,

    # --- Tools (active, high signal when they find something) ---
    "sfp_tool_nmap": 88,
    "sfp_tool_nuclei": 85,
    "sfp_tool_dnstwist": 72,
    "sfp_tool_wafw00f": 82,
    "sfp_tool_whatweb": 80,
    "sfp_tool_wappalyzer": 80,
    "sfp_tool_testsslsh": 88,
    "sfp_tool_trufflehog": 80,
    "sfp_tool_retirejs": 78,
    "sfp_tool_snallygaster": 72,
    "sfp_tool_cmseek": 78,
    "sfp_tool_nbtscan": 82,
    "sfp_tool_onesixtyone": 80,

    # --- Cloud / Storage ---
    "sfp_s3bucket": 85,
    "sfp_azureblobstorage": 85,
    "sfp_digitaloceanspace": 85,
    "sfp_googleobjectstorage": 85,
    "sfp_grayhatwarfare": 80,

    # --- Blockchain / Crypto ---
    "sfp_bitcoin": 88,
    "sfp_bitcoinabuse": 82,
    "sfp_bitcoinwhoswho": 78,
    "sfp_blockchain": 85,
    "sfp_etherscan": 85,
    "sfp_ethereum": 80,

    # --- Content / File Analysis ---
    "sfp_filemeta": 80,
    "sfp_base64": 70,
    "sfp_binstring": 65,
    "sfp_hashes": 75,
    "sfp_creditcard": 80,
    "sfp_iban": 80,
    "sfp_phone": 75,
    "sfp_names": 60,
    "sfp_email": 75,
    "sfp_errors": 72,
    "sfp_junkfiles": 70,
    "sfp_intfiles": 72,
    "sfp_countryname": 65,

    # --- Hosting / Network Infra ---
    "sfp_hosting": 82,
    "sfp_multiproxy": 78,
    "sfp_torexits": 88,
    "sfp_adblock": 72,
    "sfp_adguard_dns": 72,
    "sfp_cleanbrowsing": 72,
    "sfp_cloudflaredns": 78,
    "sfp_comodo": 72,
    "sfp_opendns": 75,
    "sfp_opennic": 70,
    "sfp_quad9": 75,
    "sfp_dns_for_family": 70,
    "sfp_fsecure_riddler": 72,
    "sfp_coinblocker": 70,
    "sfp_stevenblack_hosts": 72,
    "sfp_surbl": 78,

    # --- Misc / Feeds ---
    "sfp_abstractapi": 78,
    "sfp_abusix": 78,
    "sfp_googlemaps": 78,
    "sfp_openstreetmap": 75,
    "sfp_portscan_tcp": 92,
    "sfp_wigle": 70,
    "sfp_googlesafebrowsing": 88,
    "sfp_iknowwhatyoudownload": 75,
    "sfp_koodous": 75,
    "sfp_crxcavator": 75,
    "sfp_apple_itunes": 80,
    "sfp_openbugbounty": 78,
    "sfp_fsecure_riddler": 72,
    "sfp_open_passive_dns_database": 80,
    "sfp_voipbl": 72,
    "sfp_spyse": 80,
    "sfp_focsec": 75,
    "sfp_riskiq": 82,
    "sfp_dnsdb": 85,
    "sfp_neutrino_api": 75,
    "sfp_abstractapi": 78,
    "sfp_social": 65,
    "sfp_subdomain_takeover": 85,
    "sfp_h1nobbdde": 60,
    "sfp_zoneh": 65,
    "sfp_wikipediaedits": 60,
    "sfp_crossref": 72,
    "sfp_textmagic": 65,
    "sfp_callername": 65,
    "sfp_numverify": 72,
    "sfp_twilio": 72,
    "sfp_seon": 75,
    "sfp_sociallinks": 65,
    "sfp_venmo": 60,
    "sfp_customfeed": 70,
    "sfp_zetalytics": 80,
    "sfp_google_tag_manager": 78,
    "sfp_bingsharedip": 72,
    "sfp_hosting": 82,
    "sfp_emailcrawlr": 72,
    "sfp_debounce": 72,
    "sfp_focsec": 75,
    "sfp_neutrinoapi": 75,
    "sfp_pgp": 68,
    "sfp_circllu": 82,
    "sfp_cleantalk": 75,
}
